<?php

/**
 * @phpstan-type ShapeEntityContactperson array{
 *     id?: int,
 *     name?: string|null,
 *     connected_company_id?: int|null,
 * }
 * @phpstan-type ShapeEntityContactpersonSelectRow array{
 *     inputtype: string,
 *     value: int,
 *     label: string
 * }
 * @phpstan-type ShapeEntityContactpersonExtraRow array{
 *     id: int,
 *     name: string,
 *     shortname: string|null
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 * @property ?int $connected_company_id
 *
 * @extends SQLEntity<ShapeEntityContactperson>
 */
class EntityContactperson extends SQLEntity
{
	public const string TABLE_NAME = 'contactpersons';

	// ============================================================================
	// Error constants
	// ============================================================================

	public const int ERROR_CONTACTPERSON_ID_EMPTY = -1;
	public const int ERROR_MULTIPLE_CONTACTPERSONS = -2;
	public const int ERROR_CONTACTPERSON_NOT_FOUND = -3;

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityContactperson $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityContactperson $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityContactperson $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityContactperson $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityContactperson $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from class.ContactPersons.php)
	// ============================================================================

	/**
	 * Get contact person name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->name ?? '';
	}

	/**
	 * Get all contact persons.
	 * @return array<int, ShapeEntityContactperson>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('contactpersons');
	}

	/**
	 * Get contact persons for autocomplete select.
	 * @return array<int, ShapeEntityContactpersonSelectRow>
	 */
	public static function getListForSelect(string $term): array
	{
		$query = "SELECT cp.name, cp.id, c.shortname FROM contactpersons cp LEFT JOIN companies c ON c.id=cp.connected_company_id WHERE cp.name LIKE :term";
		$stmt = Db::instance()->prepare($query);
		$stmt->execute(['term' => "%{$term}%"]);

		$rs = $stmt->fetchAll(PDO::FETCH_ASSOC);

		$return = [];

		foreach ($rs as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['shortname'] == '' ? "{$value['name']}" : "{$value['name']} ({$value['shortname']})",
			];
		}

		return $return;
	}

	/**
	 * Get contact persons with company shortname.
	 * @return array<int, ShapeEntityContactpersonExtraRow>
	 */
	public static function getListWithExtradata(): array
	{
		$query = "
			SELECT
				cp.id,
				cp.name AS name,
				c.shortname
			FROM
				contactpersons cp
				LEFT JOIN companies c
					ON c.id = cp.connected_company_id ;";

		$stmt = Db::instance()->prepare($query);

		$stmt->execute();

		return $stmt->fetchAll(PDO::FETCH_ASSOC);
	}

	/**
	 * Get all modification history for a contact person.
	 * @return array<int, mixed>|null
	 */
	public static function getAllModificationsData(int $id): ?array
	{
		return Audit::getAllModificationsWithComments('contactpersons', $id);
	}

	/**
	 * Auto-detect contact person ID from value
	 * Value wrapped in underscores (_name_) searches by name
	 * Plain value is treated as ID.
	 */
	public static function autoDetectId(string $value): int
	{
		$value = trim($value);

		if (trim($value, '_') == '') {
			return self::ERROR_CONTACTPERSON_ID_EMPTY;
		}

		if (trim($value, '_') !== $value) {
			// find by name
			$contactpersons = DbHelper::selectMany('contactpersons', ['name' => trim($value, '_')], false, '', 'id');
		} else {
			// find by id (to check existence)
			$contactpersons = DbHelper::selectMany('contactpersons', ['id' => trim($value)], false, '', 'id');
		}

		if (count($contactpersons) == 0) {
			return self::ERROR_CONTACTPERSON_NOT_FOUND;
		}

		if (count($contactpersons) > 1) {
			return self::ERROR_MULTIPLE_CONTACTPERSONS;
		}

		return $contactpersons[0]['id'];
	}

	/**
	 * Find contact person ID by name and company ID.
	 */
	public static function getIdFromNameAndCompanyId(string $name, int $connected_company_id): ?int
	{
		$return = DbHelper::selectOne(
			table: 'contactpersons',
			where: [
				'name' => $name,
				'connected_company_id' => $connected_company_id,
			],
			cols: 'id'
		);

		return $return['id'] ?? null;
	}
}
