<?php

/**
 * @phpstan-type ShapeEntityTicket array{
 *     id?: int,
 *     title?: string|null,
 *     description?: string|null,
 *     __description?: string|null,
 *     project_id?: int|null,
 *     start_date?: string|null,
 *     end_date?: string|null,
 *     ticket_type?: int|null,
 *     ticket_state?: int|null,
 *     ticket_priority?: int|null,
 *     connected_contactperson_id?: int|null,
 *     assigned_user_id?: int|null,
 * }
 * @phpstan-type ShapeEntityTicketListRow array{
 *     id: int,
 *     title: string|null,
 *     assigned_user_id: int|null,
 *     project_id: int|null,
 *     project_name: string|null,
 *     type: string|null,
 *     priority: string|null,
 *     priority_seq: int|null,
 *     description: string|null,
 *     start_date: string|null,
 *     end_date: string|null,
 *     connected_contactperson_id: int|null,
 *     contactperson: string|null,
 *     assigned_username: string|null,
 *     shortname: string|null,
 *     state: string|null,
 *     ticket_type: int|null,
 *     tags: string
 * }
 * @phpstan-type ShapeEntityTicketSelectRow array{
 *     inputtype: string,
 *     value: int,
 *     label: string
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $title
 * @property ?string $description
 * @property ?string $__description
 * @property ?int $project_id
 * @property ?string $start_date
 * @property ?string $end_date
 * @property ?int $ticket_type
 * @property ?int $ticket_state
 * @property ?int $ticket_priority
 * @property ?int $connected_contactperson_id
 * @property ?int $assigned_user_id
 *
 * @extends SQLEntity<ShapeEntityTicket>
 */
class EntityTicket extends SQLEntity
{
	public const string TABLE_NAME = 'tickets';

	// ============================================================================
	// URL filter params configuration
	// ============================================================================

	protected static array $_enabledUrlParams = [
		'id' => 'id',
		'state' => 'allapot',
		'type' => 'tipus',
		'priority' => 'prioritas',
		'project_name' => 'projekt',
		'tag' => 'cimke',
		'contactperson' => 'kapcsolattarto',
		'assigned_username' => 'felelos',
		'nyitott' => '_nyitott',
	];

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from Tickets class hierarchy)
	// ============================================================================

	/**
	 * Get enabled URL parameters for filtering.
	 * @return array<string, string>
	 */
	public static function getEnabledUrlParams(): array
	{
		return self::$_enabledUrlParams;
	}

	/**
	 * Get tickets with extra data for list display.
	 * @param array<string, mixed> $filters
	 * @return array<int, ShapeEntityTicketListRow>
	 */
	public static function getListWithExtradata(array $filters = []): array
	{
		$skip_filters = ['nyitott', ];

		$SQLQueryFilter = new SQLQueryFilter($filters, self::$_enabledUrlParams, $skip_filters);

		$WHERE_string = "";

		if (isset($filters['nyitott'])) {
			$WHERE_string = "WHERE is_open";
		}

		$query = "
			SELECT
				t.id,
				t.title,
				t.assigned_user_id,
				p.id project_id,
				p.name project_name,
				tt.name type,
				tp.name priority,
				tp.seq priority_seq,
				t.description,
				t.start_date,
				t.end_date,
				t.connected_contactperson_id,
				cp.name AS contactperson,
				u.username AS assigned_username,
				c.shortname,
				ts.name AS state,
				t.ticket_type,
					(SELECT
						COALESCE(
							GROUP_CONCAT(DISTINCT (tags.name) SEPARATOR ', '),
							''
						)
					FROM
						tags tags
						LEFT JOIN
						tag_connections tc
						ON tc.tag_id = tags.id
					WHERE tags.context = 'tracker_ticket'
						AND tc.connected_id = t.id) AS tags
			FROM
				tickets t
				LEFT JOIN
				projects p
				ON p.id = t.project_id
				LEFT JOIN
				ticket_states ts
				ON t.ticket_state = ts.id
				LEFT JOIN
				ticket_priorities tp
				ON t.ticket_priority = tp.id
				LEFT JOIN
				contactpersons cp
				ON cp.id=t.connected_contactperson_id
				LEFT JOIN
				companies c
				ON c.id=cp.connected_company_id
				LEFT JOIN
				users u
				ON u.user_id=t.assigned_user_id
				LEFT JOIN
				ticket_types tt
				ON t.ticket_type=tt.id
			{$WHERE_string}
			" . $SQLQueryFilter->getHaving() . "
			;";

		return DbHelper::selectManyFromQuery(
			$query,
			$SQLQueryFilter->getValues()
		);
	}

	/**
	 * Get tickets for autocomplete select.
	 * @return array<int, ShapeEntityTicketSelectRow>
	 */
	public static function getListForSelect(string $term, bool $filtered): array
	{
		$term = Helpers::clearText($term);
		$term = '%' . str_replace(" ", "%", $term) . '%';

		if ($filtered) {
			$query = "SELECT t.id, t.title, CONCAT('#', t.id, ' - ', t.title) AS label FROM tickets t LEFT JOIN ticket_states ts ON t.ticket_state=ts.id WHERE ts.is_open HAVING label LIKE ? ORDER BY id";
		} else {
			$query = "SELECT t.id, t.title, CONCAT('#', t.id, ' - ', t.title) AS label FROM tickets t HAVING label LIKE ? ORDER BY id";
		}

		$tickets = DbHelper::selectManyFromQuery($query, [$term]);

		$return = [];

		foreach ($tickets as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => "#{$value['id']} - {$value['title']}",
			];
		}

		return $return;
	}

	/**
	 * Get ticket name (title) by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->title ?? '';
	}

	/**
	 * Get all modification history for a ticket.
	 * @return array<int, mixed>
	 */
	public static function getAllModificationsData(int $id): array
	{
		$query = "
SELECT
    a.audit_id,
    modify_group_id,
    trigger_type,
    tablename,
    row_id,
    triggered_datetime,
    user_id ,
    col,
    old_value,
    new_value
FROM
    " . Db::getAuditDbFromDsn() . "._audit a
    LEFT JOIN " . Db::getAuditDbFromDsn() . ".audit_data ad
        ON a.audit_id = ad.audit_id
WHERE (
        tablename = 'tickets'
        AND row_id = ?
    )
    OR (
        connected_context = 'tracker_ticket'
        AND connected_owner_id = ?
        AND tablename IN (
            'issues',
            'tag_connections',
            'comments'
        )
    )
ORDER BY triggered_datetime;
";

		$stmt = Db::instance()->prepare($query);
		$stmt->execute([
			$id,
			$id,
		]);

		$rs = $stmt->fetchAll(PDO::FETCH_ASSOC);

		$previous_row = [
			'audit_id' => null,
			'modify_group_id' => null,
			'trigger_type' => null,
			'tablename' => null,
			'row_id' => null,
			'triggered_datetime' => null,
			'user_id' => null,
			'col' => null,
			'old_value' => null,
			'new_value' => null,
		];

		$modifications = [];
		$comment_id = 0;

		foreach ($rs as $row) {
			if ($row['modify_group_id'] !== $previous_row['modify_group_id']) {
				++$comment_id;
			}

			$modifications[$comment_id]['meta']['triggered_datetime'] = $row['triggered_datetime'];
			$modifications[$comment_id]['meta']['user_id'] = $row['user_id'];

			switch ($row['tablename']) {
				case 'tickets':
					$modifications[$comment_id]['modify_data']['modifications']['audit_id'] = $row['audit_id'];
					$modifications[$comment_id]['modify_data']['modifications']['data'][$row['col']] = [
						'old_value' => $row['old_value'],
						'new_value' => $row['new_value'],
					];
					$modifications[$comment_id]['modify_data']['modifications']['trigger_type'] = $row['trigger_type'];

					break;

				case 'comments':
					$modifications[$comment_id]['modify_data']['comments'][$row['audit_id']]['data'][$row['col']] = [
						'old_value' => $row['old_value'],
						'new_value' => $row['new_value'],
					];
					$modifications[$comment_id]['modify_data']['comments'][$row['audit_id']]['trigger_type'] = $row['trigger_type'];

					break;

				case 'tag_connections':
					$modifications[$comment_id]['modify_data']['tags'][$row['trigger_type']][$row['audit_id']][$row['col']] = [
						'old_value' => $row['old_value'],
						'new_value' => $row['new_value'],
					];

					break;
			}

			$previous_row = $row;
		}

		$modifications = array_values($modifications);

		foreach ($modifications as $key => &$modification) {
			$modification['meta']['comment_id'] = $key;

			$modification['meta']['has_modifies'] = true;

			if (isset($modification['modify_data']['comments'])) {
				foreach ($modification['modify_data']['comments'] as &$comment) {
					$comment['last_data'] = EntityComment::getCommentData($comment['data']['comment_id']['old_value'] | $comment['data']['comment_id']['new_value']);
				}
			}

			$modification['modify_data']['deleted_tags'] = [];

			if (isset($modification['modify_data']['tags']['BD'])) {
				foreach ($modification['modify_data']['tags']['BD'] as $deleted_tag) {
					$modification['modify_data']['deleted_tags'][] = EntityTag::getTagName($deleted_tag['tag_id']['old_value']);
				}
			}

			$modification['modify_data']['added_tags'] = [];

			if (isset($modification['modify_data']['tags']['BI'])) {
				foreach ($modification['modify_data']['tags']['BI'] as $added_tag) {
					$modification['modify_data']['added_tags'][] = EntityTag::getTagName($added_tag['tag_id']['new_value']);
				}
			}

			$modification['modify_data']['deleted_tags'] = implode(', ', $modification['modify_data']['deleted_tags']);
			$modification['modify_data']['added_tags'] = implode(', ', $modification['modify_data']['added_tags']);

			if (isset($modification['modify_data']['comments'])) {
				$modification['modify_data']['comments'] = array_values($modification['modify_data']['comments']);
			}
		}

		return $modifications;
	}

	/**
	 * Prepare data before save - handle empty dates.
	 * @param ShapeEntityTicket $data
	 * @return ShapeEntityTicket
	 */
	protected static function _prepareSaveData(array $data): array
	{
		if (isset($data['start_date']) && empty(trim((string) $data['start_date']))) {
			$data['start_date'] = null;
		}

		if (isset($data['end_date']) && empty(trim((string) $data['end_date']))) {
			$data['end_date'] = null;
		}

		return $data;
	}

	/**
	 * {@inheritDoc}
	 */
	protected static function _doSave(array $data): static
	{
		$data = static::_prepareSaveData($data);

		return parent::_doSave($data);
	}
}
