<?php

/**
 * @phpstan-type ShapeEntityTicket_stat array{
 *     id?: int,
 *     name?: string|null,
 *     is_open?: bool|int|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 * @property bool|int|null $is_open DB returns 0/1, use loose comparison (==)
 *
 * @extends SQLEntity<ShapeEntityTicket_stat>
 */
class EntityTicket_stat extends SQLEntity
{
	public const string TABLE_NAME = 'ticket_states';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_stat $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_stat $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_stat $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_stat $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_stat $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from TicketStates class)
	// ============================================================================

	/**
	 * Get all ticket states.
	 * @return array<int, ShapeEntityTicket_stat>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('ticket_states');
	}

	/**
	 * Get ticket states for select dropdown.
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(): array
	{
		$ticket_states = DbHelper::selectMany('ticket_states');

		$return = [];

		foreach ($ticket_states as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['name'],
			];
		}

		return $return;
	}

	/**
	 * Get ticket state name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->name ?? '';
	}

	/**
	 * Get ticket state ID by name.
	 */
	public static function getIdByName(string $name): ?int
	{
		$return = DbHelper::selectOne(
			table: 'ticket_states',
			where: ['name' => $name],
			cols: 'id'
		);

		return $return['id'] ?? null;
	}
}
