<?php

/**
 * @phpstan-type ShapeEntityTicket_typ array{
 *     id?: int,
 *     name?: string|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 *
 * @extends SQLEntity<ShapeEntityTicket_typ>
 */
class EntityTicket_typ extends SQLEntity
{
	public const string TABLE_NAME = 'ticket_types';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_typ $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_typ $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_typ $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_typ $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_typ $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from TicketTypes class)
	// ============================================================================

	/**
	 * Get all ticket types.
	 * @return array<int, ShapeEntityTicket_typ>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('ticket_types');
	}

	/**
	 * Get ticket types for select dropdown.
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(): array
	{
		$ticket_types = DbHelper::selectMany('ticket_types');

		$return = [];

		foreach ($ticket_types as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['name'],
			];
		}

		return $return;
	}

	/**
	 * Get ticket type name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->name ?? '';
	}

	/**
	 * Get ticket type ID by name.
	 */
	public static function getIdByName(string $name): ?int
	{
		$return = DbHelper::selectOne(
			table: 'ticket_types',
			where: ['name' => $name],
			cols: 'id'
		);

		return $return['id'] ?? null;
	}
}
