<?php

/**
 * @phpstan-type ShapeEntityTicket_priority array{
 *     id?: int,
 *     name?: string|null,
 *     seq?: int|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 * @property ?int $seq
 *
 * @extends SQLEntity<ShapeEntityTicket_priority>
 */
class EntityTicket_priority extends SQLEntity
{
	public const string TABLE_NAME = 'ticket_priorities';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_priority $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_priority $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_priority $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_priority $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTicket_priority $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from TicketPriorities class)
	// ============================================================================

	/**
	 * Get all ticket priorities.
	 * @return array<int, ShapeEntityTicket_priority>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('ticket_priorities');
	}

	/**
	 * Get ticket priorities for select dropdown.
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(): array
	{
		$ticket_priorities = DbHelper::selectMany('ticket_priorities');

		$return = [];

		foreach ($ticket_priorities as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['name'],
			];
		}

		return $return;
	}

	/**
	 * Get ticket priority name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return t('common.not_set');
		}

		return $entity->name ?? t('common.not_set');
	}

	/**
	 * Get ticket priority ID by name.
	 */
	public static function getIdByName(string $name): ?int
	{
		$return = DbHelper::selectOne(
			table: 'ticket_priorities',
			where: ['name' => $name],
			cols: 'id'
		);

		return $return['id'] ?? null;
	}
}
