<?php

/**
 * @phpstan-type ShapeEntityProject array{
 *     id?: int,
 *     name: string,
 *     state?: int|null,
 *     connected_company_id?: int|null,
 * }
 * @phpstan-type ShapeEntityProjectListRow array{
 *     id: int,
 *     name: string,
 *     project_state: string|null,
 *     connected_company_id: int|null,
 *     company_name: string|null,
 *     shortname: string|null,
 *     tags: string|null,
 *     tags_tickets: string|null,
 *     all_tickets: int,
 *     open_tickets: int
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 * @property ?int $state
 * @property ?int $connected_company_id
 *
 * @extends SQLEntity<ShapeEntityProject>
 */
class EntityProject extends SQLEntity
{
	public const string TABLE_NAME = 'projects';

	// ============================================================================
	// Error constants
	// ============================================================================

	public const int ERROR_PROJECT_ID_EMPTY = -1;
	public const int ERROR_MULTIPLE_PROJECTS = -2;
	public const int ERROR_PROJECT_NOT_FOUND = -3;

	// ============================================================================
	// URL filter params configuration
	// ============================================================================

	protected static array $_enabledUrlParams = [
		'id' => 'id',
		'company_name' => 'ceg',
		'name' => 'nev',
		'project_state' => 'allapot',
		'issues' => 'all-issues',
		'open_issues' => 'open-issues',
		'tag' => 'cimke',
	];

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from class.Projects.php)
	// ============================================================================

	/**
	 * Get enabled URL parameters for filtering.
	 * @return array<string, string>
	 */
	public static function getEnabledUrlParams(): array
	{
		return self::$_enabledUrlParams;
	}

	/**
	 * Get all projects.
	 * @return array<int, ShapeEntityProject>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('projects');
	}

	/**
	 * Get projects with extra data (company, tags, ticket counts).
	 * @param array<string, mixed> $filters
	 * @return array<int, ShapeEntityProjectListRow>
	 */
	public static function getListWithExtradata(array $filters = []): array
	{
		$SQLQueryFilter = new SQLQueryFilter($filters, self::$_enabledUrlParams);

		$query = "
			SELECT
				p.id,
				p.name,
					(SELECT
						name
					FROM project_states ps
					WHERE ps.id=p.state)
				AS project_state,
				p.connected_company_id,
				c.name company_name,
				c.shortname,
					(SELECT
						GROUP_CONCAT(DISTINCT (name) SEPARATOR ', ')
					FROM
						tags t
						LEFT JOIN
						tag_connections tc
						ON tc.tag_id = t.id
					WHERE t.context = 'tracker_project'
						AND tc.connected_id = p.id)
				AS tags,
					(SELECT
						GROUP_CONCAT(DISTINCT (name) SEPARATOR ', ')
					FROM
						tags t
						LEFT JOIN tag_connections tc
						ON tc.tag_id = t.id
					WHERE t.context = 'tracker_ticket'
						AND tc.connected_id IN (SELECT t2.id FROM tickets t2 WHERE t2.project_id=p.id))
				AS tags_tickets,
					(SELECT
						COUNT(1)
					FROM
						tickets t
					WHERE t.project_id = p.id)
				AS all_tickets,
					(SELECT
						COUNT(1)
					FROM
						tickets t
					WHERE t.project_id = p.id
						AND t.end_date IS NULL)
				AS open_tickets
			FROM
				projects p
				LEFT JOIN
				companies c
				ON c.id = p.connected_company_id
			" . $SQLQueryFilter->getHaving() . "
			;";

		return DbHelper::selectManyFromQuery($query, $SQLQueryFilter->getValues());
	}

	/**
	 * Get projects for select dropdown.
	 * @param array<string, mixed> $filter
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(array $filter = []): array
	{
		$projects = DbHelper::selectMany('projects', $filter, false, 'name');

		$return = [];

		foreach ($projects as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['name'],
			];
		}

		return $return;
	}

	/**
	 * Get project name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->name ?? '';
	}

	/**
	 * Auto-detect project ID from value
	 * Value wrapped in underscores (_name_) searches by name
	 * Plain value is treated as ID.
	 */
	public static function autoDetectId(string $value): int
	{
		$value = trim($value);

		if (trim($value, '_') == '') {
			return self::ERROR_PROJECT_ID_EMPTY;
		}

		if (trim($value, '_') !== $value) {
			// find by name
			$projects = DbHelper::selectMany('projects', ['name' => trim($value, '_')], false, '', 'id');
		} else {
			// find by id (to check existence)
			$projects = DbHelper::selectMany('projects', ['id' => trim($value)], false, '', 'id');
		}

		if (count($projects) == 0) {
			return self::ERROR_PROJECT_NOT_FOUND;
		}

		if (count($projects) > 1) {
			return self::ERROR_MULTIPLE_PROJECTS;
		}

		return $projects[0]['id'];
	}
}
