<?php

/**
 * @phpstan-type ShapeEntityProject_stat array{
 *     id?: int,
 *     name?: string,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $name
 *
 * @extends SQLEntity<ShapeEntityProject_stat>
 */
class EntityProject_stat extends SQLEntity
{
	public const string TABLE_NAME = 'project_states';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject_stat $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject_stat $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject_stat $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject_stat $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityProject_stat $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from class.Projects.php)
	// ============================================================================

	/**
	 * Get all project states.
	 * @return array<int, ShapeEntityProject_stat>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('project_states');
	}

	/**
	 * Get project states for select dropdown.
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(): array
	{
		$project_states = DbHelper::selectMany('project_states');

		$return = [];

		foreach ($project_states as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $value['name'],
			];
		}

		return $return;
	}

	/**
	 * Get project state name by ID.
	 */
	public static function getName(int $id): string
	{
		$entity = static::findById($id);

		if ($entity === null) {
			return '';
		}

		return $entity->name ?? '';
	}

	/**
	 * Get project state ID by name.
	 */
	public static function getIdByName(string $name): ?int
	{
		$return = DbHelper::selectOne(
			table: 'project_states',
			where: ['name' => $name],
			cols: 'id'
		);

		return $return['id'] ?? null;
	}
}
