<?php

/**
 * @phpstan-type ShapeEntityTimetracker array{
 *     id?: int,
 *     description?: string|null,
 *     connected_ticket_id?: int|null,
 *     start_time?: string|null,
 *     end_time?: string|null,
 *     user_id?: int|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $description
 * @property ?int $connected_ticket_id
 * @property ?string $start_time
 * @property ?string $end_time
 * @property ?int $user_id
 *
 * @extends SQLEntity<ShapeEntityTimetracker>
 */
class EntityTimetracker extends SQLEntity
{
	public const string TABLE_NAME = 'timetracker';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTimetracker $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTimetracker $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTimetracker $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTimetracker $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTimetracker $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (migrated from class.TimeTracker.php)
	// ============================================================================

	/**
	 * Get all timetracker entries.
	 * @return array<int, ShapeEntityTimetracker>
	 */
	public static function getList(): array
	{
		$query = "SELECT * FROM timetracker ORDER BY id";

		return DbHelper::selectManyFromQuery($query);
	}

	/**
	 * Delete an entry by ID.
	 */
	public static function deleteEntry(int $id): bool
	{
		return DbHelper::deleteHelper('timetracker', $id);
	}

	/**
	 * Prepare data before save - handle empty values for FK fields.
	 * @param ShapeEntityTimetracker $data
	 * @return ShapeEntityTimetracker
	 */
	protected static function _prepareSaveData(array $data): array
	{
		if (isset($data['connected_ticket_id']) && trim((string) $data['connected_ticket_id'], '_') == '') {
			$data['connected_ticket_id'] = null;
		}

		if (isset($data['user_id']) && trim((string) $data['user_id'], '_') == '') {
			$data['user_id'] = null;
		}

		return $data;
	}

	/**
	 * {@inheritDoc}
	 */
	protected static function _doSave(array $data): static
	{
		$data = static::_prepareSaveData($data);

		return parent::_doSave($data);
	}
}
