<?php

/**
 * @phpstan-type ShapeEntityCompany array{
 *     id?: int,
 *     shortname?: string|null,
 *     name?: string|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $shortname
 * @property ?string $name
 *
 * @extends SQLEntity<ShapeEntityCompany>
 */
class EntityCompany extends SQLEntity
{
	public const string TABLE_NAME = 'companies';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityCompany $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityCompany $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityCompany $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityCompany $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityCompany $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom methods (safe to add, will not be overwritten by generator)
	// ============================================================================

	public const int ERROR_COMPANY_ID_EMPTY = -1;
	public const int ERROR_MULTIPLE_COMPANIES = -2;
	public const int ERROR_COMPANY_NOT_FOUND = -3;

	/**
	 * Get company display name: "Name (Shortname)" or just "Name" if no shortname.
	 */
	public static function getLongName(int $id): string
	{
		$company = self::findById($id);

		if (is_null($company)) {
			return '';
		}

		if (empty($company->shortname)) {
			return (string) $company->name;
		}

		return "{$company->name} ({$company->shortname})";
	}

	/**
	 * Get all companies as array.
	 *
	 * @return array<int, array<string, mixed>>
	 */
	public static function getList(): array
	{
		return DbHelper::selectMany('companies');
	}

	/**
	 * Get companies formatted for select dropdown.
	 *
	 * @param array<string, mixed> $filter
	 * @return array<int, array{inputtype: string, value: int, label: string}>
	 */
	public static function getListForSelect(array $filter = []): array
	{
		$companies = DbHelper::selectMany('companies', $filter, false, 'name', '*', 'OR');

		$return = [];

		foreach ($companies as $value) {
			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => "{$value['name']} ({$value['shortname']})",
			];
		}

		return $return;
	}

	/**
	 * Auto-detect company ID from value (ID or _shortname_).
	 */
	public static function autoDetectId(string $value): int
	{
		$value = trim($value);

		if (trim($value, '_') == '') {
			return self::ERROR_COMPANY_ID_EMPTY;
		}

		if (trim($value, '_') !== $value) {
			// find by shortname
			$company = self::findFirst(['shortname' => trim($value, '_')]);
		} else {
			// find by id (to check existence)
			$company = self::findById((int) trim($value));
		}

		if (is_null($company)) {
			return self::ERROR_COMPANY_NOT_FOUND;
		}

		return (int) $company->id;
	}

	/**
	 * Get company ID by name.
	 */
	public static function getIdFromName(string $name): ?int
	{
		$company = self::findFirst(['name' => $name]);

		return $company?->id;
	}

	/**
	 * Get all modifications data for audit trail.
	 */
	public static function getAllModificationsData(int $id): ?array
	{
		return Audit::getAllModificationsWithComments('companies', $id);
	}
}
